### ISSUE TITLE
Bug: announce_highest in hog project can't pass all tests

### ISSUE THREAD

**Issue by Mike-Dai** [czahie/CS61A#1]
Hi, @czahie. Thank you for sharing solution of hog project! It helps me a lot. But it seems that `announce_highest` function in phase2 can not pass the test. Here is the trace back.
```
>>> # The following function call checks if the behavior of f1 changes,
>>> # perhaps due to a side effect other than printing. The only side
>>> # effect of a commentary function should be to print.
>>> f2_again = f1(11, 1)

# Error: expected
#     1 point! That's the biggest gain yet for Player 1
# but got


Run only this test case with "python3 ok -q 07 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case
```

The bug confused me for hours. I've written the function in another way and it passed the test. 
```python
def announce_highest(who, previous_high=0, previous_score=0):
    assert who == 0 or who == 1, 'The who argument should indicate a player.'
    # BEGIN PROBLEM 7
    def say(score0, score1):
        nonlocal previous_high, previous_score
        if who == 0:
            score = score0
        elif who == 1:
            score = score1
        current_score = score - previous_score
        if current_score > previous_high:
            if current_score == 1:
                print("1 point! That's the biggest gain yet for Player", who)
            else:
                print(current_score, "points! That's the biggest gain yet for Player", who)
            return announce_highest(who, current_score, score)
        return announce_highest(who, previous_high, score)
    return say
    # END PROBLEM 7
```
But I still can't figure out why the first implementation is wrong. I will appreciate it if you can help me.

**Comment by czahie** [comment]
Hi! Thanks for your issue. I just checked my code I think the problem is because of the line:
`previous_score = score0` or `previous_score = score1`. The `previous_score` is updated every time I call `say`. Therefore, if you call the function for the second time, there would be no print messages. If I remembered it correctly,  my code passed all the test cases back to the course of 2017 Fall. So maybe they have changed the rule. Thanks again for your report anyway!

**Comment by Mike-Dai** [comment]
Thanks! I take the version of 2018 Spring and they might add more tests.

**Comment by pangjac** [comment]
Hi @czahie , it is very nice for sharing the notes with us.  I have a quick question, where do we get the `OK` credential if not enrolled in Berkeley, how do you pass all tests if without `OK`?  I read [cs61 account trouble shooting](https://cs61a.org/articles/account-troubleshooting.html#ok-account), but still confused about their autograder system.
Thank you so much!

**Comment by czahie** [comment]
@pangjac Actually, I used `ok`. I think there's a way to use `ok` locally, meaning that you can use `ok` without a Berkeley email. But I'm not sure whether they've updated this or not.

**Comment by gclintj** [comment]
> Hi! Thanks for your issue. I just checked my code I think the problem is because of the line:
> `previous_score = score0` or `previous_score = score1`. The `previous_score` is updated every time I call `say`. Therefore, if you call the function for the second time, there would be no print messages. If I remembered it correctly, my code passed all the test cases back to the course of 2017 Fall. So maybe they have changed the rule. Thanks again for your report anyway!

Thanks!
I don't fully understand the command "nonlocal", but I believe it causes the problem that the function gives a different result when later called.
@Mike-Dai 's solution also makes it unnecessary to use the "nonlocal" command. 
I think it is what the instruction means: "1) Rather than reassigning [var] to its new value, create a new variable to hold that new value. Use that new variable in future calculations."
Thank you both! Now I understand much better about this problem.
BTW, potentially "previous_high" is another headache, with similar two issues.
